import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const clubs = [
    // Rugby Clubs (15)
    {
      name: 'Docklands Rugby Football Club',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Docklands+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Docklands+RFC+1',
        'https://via.placeholder.com/600x400.png?text=Docklands+RFC+2'
      ],
      latitude: 51.5079,
      longitude: 0.0280,
      social: 'Competitive',
      costPerMonth: 55,
      ageGroup: '18+',
      memberCount: 130,
      trainingFreq: 3,
      hasGym: true,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'A competitive club at the heart of Docklands offering three training sessions per week and well-equipped changing facilities.'
    },
    {
      name: 'Camden Lions RFC',
      sport: 'rugby',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Camden+Lions+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Camden+Lions+1',
        'https://via.placeholder.com/600x400.png?text=Camden+Lions+2'
      ],
      latitude: 51.5390,
      longitude: -0.1430,
      social: 'Social',
      costPerMonth: 45,
      ageGroup: 'All Ages',
      memberCount: 90,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Friendly, beginner-focused rugby club in Camden with a loyal community and on-site cafe.'
    },
    {
      name: 'Greenwich Warriors RFC',
      sport: 'rugby',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Greenwich+Warriors+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Greenwich+Warriors+1',
        'https://via.placeholder.com/600x400.png?text=Greenwich+Warriors+2'
      ],
      latitude: 51.4821,
      longitude: 0.0031,
      social: 'Competitive',
      costPerMonth: 60,
      ageGroup: '18+',
      memberCount: 160,
      trainingFreq: 4,
      hasGym: true,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: false,
      description: 'High-performance rugby program in Greenwich focused on advanced skills and weekly fixtures.'
    },
    {
      name: 'Notting Hill Nomads RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Notting+Hill+Nomads+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Notting+Hill+Nomads+1',
        'https://via.placeholder.com/600x400.png?text=Notting+Hill+Nomads+2'
      ],
      latitude: 51.5090,
      longitude: -0.1965,
      social: 'Competitive',
      costPerMonth: 50,
      ageGroup: '18+',
      memberCount: 110,
      trainingFreq: 3,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Established club in Notting Hill offering mid-week training and weekend matches across London.'
    },
    {
      name: 'West End Pirates RFC',
      sport: 'rugby',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=West+End+Pirates+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=West+End+Pirates+1',
        'https://via.placeholder.com/600x400.png?text=West+End+Pirates+2'
      ],
      latitude: 51.5138,
      longitude: -0.1365,
      social: 'Social',
      costPerMonth: 40,
      ageGroup: 'All Ages',
      memberCount: 75,
      trainingFreq: 1,
      hasGym: false,
      hasPool: false,
      hasParking: false,
      hasShowers: false,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: false,
      description: 'Casual rugby sessions in the heart of the West End, perfect for newcomers and tourists.'
    },
    {
      name: 'Shoreditch Sharks RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Shoreditch+Sharks+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Shoreditch+Sharks+1',
        'https://via.placeholder.com/600x400.png?text=Shoreditch+Sharks+2'
      ],
      latitude: 51.5245,
      longitude: -0.0754,
      social: 'Competitive',
      costPerMonth: 52,
      ageGroup: '18+',
      memberCount: 100,
      trainingFreq: 2,
      hasGym: true,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Dynamic rugby club in Shoreditch with modern gym facilities and social events.'
    },
    {
      name: 'Battersea Bears RFC',
      sport: 'rugby',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Battersea+Bears+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Battersea+Bears+1',
        'https://via.placeholder.com/600x400.png?text=Battersea+Bears+2'
      ],
      latitude: 51.4745,
      longitude: -0.1500,
      social: 'Competitive',
      costPerMonth: 65,
      ageGroup: '18+',
      memberCount: 180,
      trainingFreq: 4,
      hasGym: true,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: true,
      hasDisabledAccess: false,
      description: 'Elite rugby training near Battersea Park with top-level coaches and modern amenities.'
    },
    {
      name: 'Hackney Hawks RFC',
      sport: 'rugby',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Hackney+Hawks+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Hackney+Hawks+1',
        'https://via.placeholder.com/600x400.png?text=Hackney+Hawks+2'
      ],
      latitude: 51.5450,
      longitude: -0.0550,
      social: 'Social',
      costPerMonth: 48,
      ageGroup: 'All Ages',
      memberCount: 85,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Community-oriented rugby club in Hackney welcoming players of all backgrounds.'
    },
    {
      name: 'Chelsea Chargers RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Chelsea+Chargers+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Chelsea+Chargers+1',
        'https://via.placeholder.com/600x400.png?text=Chelsea+Chargers+2'
      ],
      latitude: 51.4875,
      longitude: -0.1680,
      social: 'Competitive',
      costPerMonth: 58,
      ageGroup: '18+',
      memberCount: 140,
      trainingFreq: 3,
      hasGym: true,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: true,
      hasLifts: true,
      hasDisabledAccess: true,
      description: 'Highly competitive rugby club in Chelsea with excellent training and social calendar.'
    },
    {
      name: 'Southbank Spartans RFC',
      sport: 'rugby',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Southbank+Spartans+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Southbank+Spartans+1',
        'https://via.placeholder.com/600x400.png?text=Southbank+Spartans+2'
      ],
      latitude: 51.5065,
      longitude: -0.1150,
      social: 'Social',
      costPerMonth: 42,
      ageGroup: 'All Ages',
      memberCount: 95,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: false,
      description: 'Laid-back rugby club on the Southbank, ideal for newcomers and occasional players.'
    },
    {
      name: 'Islington Irons RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Islington+Irons+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Islington+Irons+1',
        'https://via.placeholder.com/600x400.png?text=Islington+Irons+2'
      ],
      latitude: 51.5380,
      longitude: -0.1020,
      social: 'Competitive',
      costPerMonth: 53,
      ageGroup: '18+',
      memberCount: 125,
      trainingFreq: 3,
      hasGym: true,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Well-established club in Islington with strong focus on skill development and match play.'
    },
    {
      name: 'Tower Hamlets Titans RFC',
      sport: 'rugby',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Tower+Hamlets+Titans+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Tower+Hamlets+Titans+1',
        'https://via.placeholder.com/600x400.png?text=Tower+Hamlets+Titans+2'
      ],
      latitude: 51.5155,
      longitude: -0.0350,
      social: 'Competitive',
      costPerMonth: 62,
      ageGroup: '18+',
      memberCount: 170,
      trainingFreq: 4,
      hasGym: true,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: true,
      hasDisabledAccess: false,
      description: 'Elite-level club in Tower Hamlets with rigorous training and London-wide fixtures.'
    },
    {
      name: 'Covent Garden Crusaders RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Covent+Garden+Crusaders+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Covent+Garden+Crusaders+1',
        'https://via.placeholder.com/600x400.png?text=Covent+Garden+Crusaders+2'
      ],
      latitude: 51.5115,
      longitude: -0.1245,
      social: 'Social',
      costPerMonth: 47,
      ageGroup: 'All Ages',
      memberCount: 80,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Accessible club for players of all levels in the vibrant Covent Garden area.'
    },
    {
      name: 'Westminster Wildcats RFC',
      sport: 'rugby',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Westminster+Wildcats+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Westminster+Wildcats+1',
        'https://via.placeholder.com/600x400.png?text=Westminster+Wildcats+2'
      ],
      latitude: 51.4975,
      longitude: -0.1357,
      social: 'Competitive',
      costPerMonth: 59,
      ageGroup: '18+',
      memberCount: 150,
      trainingFreq: 3,
      hasGym: true,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: true,
      hasDisabledAccess: false,
      description: 'Competitive rugby in Westminster with modern facilities and experienced coaches.'
    },
    {
      name: 'Hampstead Hill RFC',
      sport: 'rugby',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Hampstead+Hill+RFC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Hampstead+Hill+1',
        'https://via.placeholder.com/600x400.png?text=Hampstead+Hill+2'
      ],
      latitude: 51.5565,
      longitude: -0.1785,
      social: 'Social',
      costPerMonth: 50,
      ageGroup: 'All Ages',
      memberCount: 100,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Hilly training grounds and friendly atmosphere at Hampstead Hill RFC.'
    },

    // Football Clubs (5)
    {
      name: 'East London Eagles FC',
      sport: 'football',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=East+London+Eagles+FC',
      images: [
        'https://via.placeholder.com/600x400.png?text=East+London+Eagles+1',
        'https://via.placeholder.com/600x400.png?text=East+London+Eagles+2'
      ],
      latitude: 51.5150,
      longitude: 0.0500,
      social: 'Competitive',
      costPerMonth: 35,
      ageGroup: '18+',
      memberCount: 85,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Community football club in East London with midweek training and weekend league matches.'
    },
    {
      name: 'Westminster United FC',
      sport: 'football',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Westminster+United+FC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Westminster+United+1',
        'https://via.placeholder.com/600x400.png?text=Westminster+United+2'
      ],
      latitude: 51.4980,
      longitude: -0.1350,
      social: 'Competitive',
      costPerMonth: 40,
      ageGroup: '18+',
      memberCount: 120,
      trainingFreq: 3,
      hasGym: true,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: false,
      description: 'Premier football club in Westminster competing in local amateur leagues.'
    },
    {
      name: 'South London Strikers FC',
      sport: 'football',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=South+London+Strikers+FC',
      images: [
        'https://via.placeholder.com/600x400.png?text=South+London+Strikers+1',
        'https://via.placeholder.com/600x400.png?text=South+London+Strikers+2'
      ],
      latitude: 51.4600,
      longitude: -0.1200,
      social: 'Social',
      costPerMonth: 30,
      ageGroup: 'All Ages',
      memberCount: 60,
      trainingFreq: 1,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: false,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Laid-back football club on the south side of the Thames, perfect for casual players.'
    },
    {
      name: 'North London Nomads FC',
      sport: 'football',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=North+London+Nomads+FC',
      images: [
        'https://via.placeholder.com/600x400.png?text=North+London+Nomads+1',
        'https://via.placeholder.com/600x400.png?text=North+London+Nomads+2'
      ],
      latitude: 51.5833,
      longitude: -0.1010,
      social: 'Competitive',
      costPerMonth: 38,
      ageGroup: '18+',
      memberCount: 95,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Dynamic football club in North London with regular tournaments and friendly rivalries.'
    },
    {
      name: 'Kingston Kickers FC',
      sport: 'football',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Kingston+Kickers+FC',
      images: [
        'https://via.placeholder.com/600x400.png?text=Kingston+Kickers+1',
        'https://via.placeholder.com/600x400.png?text=Kingston+Kickers+2'
      ],
      latitude: 51.4123,
      longitude: -0.3007,
      social: 'Social',
      costPerMonth: 28,
      ageGroup: 'All Ages',
      memberCount: 70,
      trainingFreq: 1,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Community-focused football club in Kingston with family-friendly sessions.'
    },

    // Tennis Clubs (5)
    {
      name: 'Kensington Tennis Club',
      sport: 'tennis',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Kensington+Tennis+Club',
      images: [
        'https://via.placeholder.com/600x400.png?text=Kensington+Tennis+1',
        'https://via.placeholder.com/600x400.png?text=Kensington+Tennis+2'
      ],
      latitude: 51.5030,
      longitude: -0.1880,
      social: 'Social',
      costPerMonth: 60,
      ageGroup: 'All Ages',
      memberCount: 50,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Scenic courts in Kensington Gardens, offering group lessons and casual play.'
    },
    {
      name: "Regent's Park Tennis Association",
      sport: 'tennis',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Regents+Park+Tennis',
      images: [
        'https://via.placeholder.com/600x400.png?text=Regents+Park+1',
        'https://via.placeholder.com/600x400.png?text=Regents+Park+2'
      ],
      latitude: 51.5313,
      longitude: -0.1569,
      social: 'Competitive',
      costPerMonth: 75,
      ageGroup: '18+',
      memberCount: 80,
      trainingFreq: 3,
      hasGym: false,
      hasPool: false,
      hasParking: false,
      hasShowers: true,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Competitive tennis association with ladder tournaments and weekly coaching.'
    },
    {
      name: 'Wimbledon Park Tennis Club',
      sport: 'tennis',
      expLevel: 'advanced',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Wimbledon+Park+Tennis',
      images: [
        'https://via.placeholder.com/600x400.png?text=Wimbledon+Park+1',
        'https://via.placeholder.com/600x400.png?text=Wimbledon+Park+2'
      ],
      latitude: 51.4487,
      longitude: -0.2103,
      social: 'Competitive',
      costPerMonth: 80,
      ageGroup: '18+',
      memberCount: 100,
      trainingFreq: 4,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: false,
      description: 'Prestigious tennis club adjacent to Wimbledon Grounds, famous for high-level coaching.'
    },
    {
      name: 'Clapham Common Tennis Club',
      sport: 'tennis',
      expLevel: 'beginner',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Clapham+Common+Tennis',
      images: [
        'https://via.placeholder.com/600x400.png?text=Clapham+Common+1',
        'https://via.placeholder.com/600x400.png?text=Clapham+Common+2'
      ],
      latitude: 51.4620,
      longitude: -0.1385,
      social: 'Social',
      costPerMonth: 45,
      ageGroup: 'All Ages',
      memberCount: 40,
      trainingFreq: 1,
      hasGym: false,
      hasPool: false,
      hasParking: false,
      hasShowers: false,
      hasCafe: false,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Affordable and friendly tennis club on Clapham Common, ideal for casual play.'
    },
    {
      name: 'Richmond Lawn Tennis Club',
      sport: 'tennis',
      expLevel: 'intermediate',
      coverImg: 'https://via.placeholder.com/600x400.png?text=Richmond+Lawn+Tennis',
      images: [
        'https://via.placeholder.com/600x400.png?text=Richmond+Lawn+1',
        'https://via.placeholder.com/600x400.png?text=Richmond+Lawn+2'
      ],
      latitude: 51.4612,
      longitude: -0.3033,
      social: 'Competitive',
      costPerMonth: 70,
      ageGroup: '18+',
      memberCount: 60,
      trainingFreq: 2,
      hasGym: false,
      hasPool: false,
      hasParking: true,
      hasShowers: true,
      hasCafe: true,
      hasLifts: false,
      hasDisabledAccess: true,
      description: 'Charming riverside tennis club in Richmond with mix of social and competitive play.'
    }
  ];

  await prisma.club.createMany({
    data: clubs,
    skipDuplicates: true,
  });

  console.log(`✅ Inserted ${clubs.length} clubs into the database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
